# Generated by Django 3.0.5 on 2020-06-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='adopciones/images')),
                ('edad_aprox', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_rescate', models.DateField()),
                ('fecha_adopcion', models.DateField()),
            ],
        ),
    ]
