# Generated by Django 3.0.5 on 2020-06-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_auto_20200617_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_adopcion',
            field=models.DateField(blank=True),
        ),
    ]
